name: kubernetes-preview-github-action
description: Create Kubernetes preview apps in PRs
runs:
  using: node12
  main: dist/index.js
branding:
  icon: aperture
  color: white
inputs:
  GITHUB_TOKEN:
    description: Github token
    required: true
  domain:
    description: Base domain
    required: true
  server:
    description: Kubernetes server url
    required: true
  token:
    description: Kubernetes user token
    required: true
  cert:
    description: Kubernetes certificate
    required: true
  image:
    description: Image to deploy
    required: true
  manifestPath:
    description: Path to Kubernetes manifest to apply
    required: true
