name: kubernetes-preview-github-action
description: Destroy deployed Kubernetes preview apps in PRs
runs:
  using: node12
  main: index.js
branding:
  icon: aperture
  color: white
inputs:
  GITHUB_TOKEN:
    description: Github token
    required: true
  namespace:
    description: Namespace to deploy into
    required: true
  kubeconfig:
    description: Path to kubeconfig
    required: true
  specsPath:
    description: Path to Kubernetes specs to destroy
    required: true
