apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: preview-wildcard
spec:
  acme:
    config:
      - dns01:
          provider: NAME_OF_PROVIDER
        domains:
          - '*.preview.domain.tld'
  dnsNames:
    - '*.preview.domain.tld'
  secretName: preview-wildcard-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
