apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "preview.fullname" . }}
  labels:
    {{- include "preview.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "preview.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "preview.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: http
            containerPort: 80
        env:
          - name: DOMAIN
            value: {{ required "ingress.domain is required" .Values.ingress.domain }}
          - name: NAMESPACE
            value: {{ .Values.ingress.namespace | default .Release.Namespace }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        readinessProbe:
          initialDelaySeconds: 30
          httpGet:
            path: /health
            port: 80
